# Generated by Django 5.1.7 on 2025-03-31 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiniSklepApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nazwa',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cena',
            new_name='price',
        ),
    ]
